Sending 80000000 Satoshi with fee of 20000000
An error occurred: HTTPSConnectionPool(host='api.blockcypher.com', port=443): Max retries exceeded with url: /v1/doge/main/addrs/D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V/full?token=78bc3fb28dd94634879c8b06494b06e0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000258CF6A1610>: Failed to resolve 'api.blockcypher.com' ([Errno 11001] getaddrinfo failed)"))
Traceback (most recent call last):
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000258CF6A1610>: Failed to resolve 'api.blockcypher.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.blockcypher.com', port=443): Max retries exceeded with url: /v1/doge/main/addrs/D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V/full?token=78bc3fb28dd94634879c8b06494b06e0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000258CF6A1610>: Failed to resolve 'api.blockcypher.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\cryptoEscrow\test10.py", line 50, in send_doge_transaction
    address_details = get_address_full(address=doge_address, coin_symbol='doge', api_key=api_token)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\blockcypher\api.py", line 221, in get_address_full
    r = requests.get(url, params=params, verify=True, timeout=TIMEOUT_IN_SECONDS)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.blockcypher.com', port=443): Max retries exceeded with url: /v1/doge/main/addrs/D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V/full?token=78bc3fb28dd94634879c8b06494b06e0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000258CF6A1610>: Failed to resolve 'api.blockcypher.com' ([Errno 11001] getaddrinfo failed)"))

Sending 80000000 Satoshi with fee of 20000000
UTXO value: 100000000
Unsigned TX: {'errors': [{'error': 'Not enough funds after fees in 1 inputs to pay for 1 outputs, missing -49606400.'}], 'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'medium', 'relayed_by': '2409:40c4:2033:6e6b:c58b:e92d:d9d5:a488', 'received': '2024-08-13T05:18:38.289124035Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}
Signed signatures: ['3045022100f2083efeb9d5f972f81614a412e9513edaa903241903d8a94d4a14cd7981ce5f022005ce2b7e17f0193d37fba4bd6974ddd866fcc0bd604f34f079c2ee00a05191d3']
Broadcasting TX
An error occurred: {'errors': [{'error': 'Not enough funds after fees in 1 inputs to pay for 1 outputs, missing -49606400.'}], 'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'medium', 'relayed_by': '2409:40c4:2033:6e6b:c58b:e92d:d9d5:a488', 'received': '2024-08-13T05:18:38.289124035Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}
Traceback (most recent call last):
  File "E:\cryptoEscrow\test10.py", line 98, in send_doge_transaction
    response = broadcast_signed_transaction(unsigned_tx=unsigned_tx, signatures=tx_signatures, pubkeys=pubkey_list, coin_symbol='doge', api_key=api_token)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\blockcypher\api.py", line 1606, in broadcast_signed_transaction
    assert 'errors' not in unsigned_tx, unsigned_tx
AssertionError: {'errors': [{'error': 'Not enough funds after fees in 1 inputs to pay for 1 outputs, missing -49606400.'}], 'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'medium', 'relayed_by': '2409:40c4:2033:6e6b:c58b:e92d:d9d5:a488', 'received': '2024-08-13T05:18:38.289124035Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}

An error occurred: non-hexadecimal number found in fromhex() arg at position 2
Traceback (most recent call last):
  File "E:\cryptoEscrow\test10.py", line 35, in send_doge_transaction
    doge_private_key_wif = hex_to_wif(doge_private_key_hex)
  File "E:\cryptoEscrow\test10.py", line 15, in hex_to_wif
    first_sha256 = hashlib.sha256(bytes.fromhex(extended_key)).hexdigest()
ValueError: non-hexadecimal number found in fromhex() arg at position 2

An error occurred: non-hexadecimal number found in fromhex() arg at position 0
Traceback (most recent call last):
  File "E:\cryptoEscrow\test10.py", line 36, in send_doge_transaction
    doge_public_key_hex = privkey_to_pubkey(doge_private_key_hex)
  File "E:\cryptoEscrow\test10.py", line 24, in privkey_to_pubkey
    priv_key = SigningKey.from_string(bytes.fromhex(hex_key), curve=SECP256k1)
ValueError: non-hexadecimal number found in fromhex() arg at position 0

Sending 80000000 Satoshi with fee of 20000000
UTXO value: 100000000
Unsigned TX: {'errors': [{'error': 'Not enough funds after fees in 1 inputs to pay for 1 outputs, missing -47065000.'}], 'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'medium', 'relayed_by': '2409:40c4:2033:6e6b:c58b:e92d:d9d5:a488', 'received': '2024-08-13T05:43:25.032320897Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}
Signed signatures: ['3045022100d0b078e37af055491cdaf0c4265ebea0a05e2ac0bff3b86f21d5cc2e9cf5a90002200f4e9f9a471ca2f218fd8ed25e7cedc28595320759bbcd532f64bd5f60dc5379']
Broadcasting TX
An error occurred: {'errors': [{'error': 'Not enough funds after fees in 1 inputs to pay for 1 outputs, missing -47065000.'}], 'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'medium', 'relayed_by': '2409:40c4:2033:6e6b:c58b:e92d:d9d5:a488', 'received': '2024-08-13T05:43:25.032320897Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}
Traceback (most recent call last):
  File "E:\cryptoEscrow\test10.py", line 98, in send_doge_transaction
    response = broadcast_signed_transaction(unsigned_tx=unsigned_tx, signatures=tx_signatures, pubkeys=pubkey_list, coin_symbol='doge', api_key=api_token)
  File "C:\Users\DV\AppData\Local\Programs\Python\Python39\lib\site-packages\blockcypher\api.py", line 1606, in broadcast_signed_transaction
    assert 'errors' not in unsigned_tx, unsigned_tx
AssertionError: {'errors': [{'error': 'Not enough funds after fees in 1 inputs to pay for 1 outputs, missing -47065000.'}], 'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'medium', 'relayed_by': '2409:40c4:2033:6e6b:c58b:e92d:d9d5:a488', 'received': '2024-08-13T05:43:25.032320897Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}

Sending 80000000 Satoshi with fee of 20000000
UTXO value: 100000000
Unsigned TX: {'tx': {'block_height': -1, 'block_index': -1, 'hash': '1085ad8466645b694876c37b8c64be416ffa9f03c3338cb3bbb7ab941e226c1e', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 85, 'preference': 'low', 'relayed_by': '2409:40c4:2033:6e6b:4806:e51c:cb3:4b9f', 'received': '2024-08-13T05:47:22.545340959Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['bf0fee19ca97af5b83a05f73f35fa8f832f2ed713d220a7d3935e16822f39222']}
Signed signatures: ['3045022100f2083efeb9d5f972f81614a412e9513edaa903241903d8a94d4a14cd7981ce5f022005ce2b7e17f0193d37fba4bd6974ddd866fcc0bd604f34f079c2ee00a05191d3']
Broadcasting TX
Transaction hash: 82984c169ba8ba218ef5c42c8613969de403e14171a7ea751df9fd9ceb6e5be9
Transaction Push Response: {'tx': {'block_height': -1, 'block_index': -1, 'hash': '82984c169ba8ba218ef5c42c8613969de403e14171a7ea751df9fd9ceb6e5be9', 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V', 'DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'total': 80000000, 'fees': 20000000, 'size': 192, 'preference': 'high', 'relayed_by': '2409:40c4:2033:6e6b:4806:e51c:cb3:4b9f', 'received': '2024-08-13T05:47:23.779842978Z', 'ver': 1, 'double_spend': False, 'vin_sz': 1, 'vout_sz': 1, 'confirmations': 0, 'inputs': [{'prev_hash': 'c9981210ff8071d29bc197c43cd22d5231f8548b1533d336025fdc5c615cd261', 'output_index': 0, 'script': '483045022100f2083efeb9d5f972f81614a412e9513edaa903241903d8a94d4a14cd7981ce5f022005ce2b7e17f0193d37fba4bd6974ddd866fcc0bd604f34f079c2ee00a05191d3012102c5127e60e50bcbca1045d0a3cd9ec0699b1e767895a07d8980ad8c17bbfd4a69', 'output_value': 100000000, 'sequence': 4294967295, 'addresses': ['D9WbyBSF8gxyEv2cVWPF5sm9chv7CrbA3V'], 'script_type': 'pay-to-pubkey-hash', 'age': 5333950}], 'outputs': [{'value': 80000000, 'script': '76a914c00f41857d13be1459eab36ffc0160cedb92d42788ac', 'addresses': ['DNecZ6FhDMiZ7rrXJkJFiVjLC7QXAY5m2G'], 'script_type': 'pay-to-pubkey-hash'}]}, 'tosign': ['']}
